version: "3.8"

services:
  postgres-db:
    image: postgres:17
    container_name: postgres-db
    environment:
      POSTGRES_USER: tms-app
      POSTGRES_PASSWORD: password
      POSTGRES_DB: tms
    ports:
      - "5433:5432"
