spring:
  datasource:
    username: tms-app
    password: password
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/tms?currentSchema=model
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    default-schema: model
    liquibase-schema: public
    change-log: classpath:db/changelog/changelog.xml
